smallstep/crypto

go.sum, keyutil/key.go, keyutil/key_test.go
This PR moves the package `github.com/smallstep/cli/crypto/keys` to this repo. At the same time, it adds the missing tests and adds the method `GenerateSigner` that returns a `crypto.Signer` instead of just interfaces.
=> Add keyutil package

x509util/certificate.go, x509util/certificate_test.go
This PR creates a certificate template without enforcing the CSR signature algorithm when no JSON templates are used.
This was causing step-ca failing to start with RSA keys.
=> Do not enforce signature algorithm when no templates are used.

x509util/certificate.go, x509util/certificate_test.go, x509util/extensions.go, x509util/extensions_test.go, x509util/testdata/fullsimple.tpl
This PR adds support for UnknownExtKeyUsage in certificate templates. UnknownExtKeyUsage are extended key usages not known by crypto/x509.
Fixes smallstep/certificates#361
=> Add support for UnknownExtKeyUsage.

x509util/certificate.go, x509util/certificate_request.go, x509util/certificate_request_test.go
This PR ignores the SignatureAlgorithm when no templates are used or in the template variable `.Insecure.CR`.
If SignatureAlgorithm is set in those cases, x509.CreateCertificate will fail if the signer cannot sign with that algorithm, e.g: RSA signer trying to sign ECDSA-SHA256.
This PR fixes some problematic cases with https://github.com/smallstep/crypto/pull/7
=> Do not enforce signature algorithm.

x509util/options_test.go, x509util/templates.go
This PR adds a new template were only the SANs and subject is read from the CR. The key usage and extended key usages are set in the template.
This template would become the default in k8ssa and admin-OIDC provisioners instead of using `{{ toJson .Insecure.CR }}`
=> Create a new default template for admin provisioners.

x509util/certificate_test.go, x509util/extensions.go, x509util/extensions_test.go, x509util/testdata/opcua.tpl
This PR adds the basic constraints extension if they are defined in the template, even if IsCA is set to false. Apparently, this might be a requirement for OPC UA (OPC Unified Architecture) servers. See https://github.com/smallstep/certificates#426
=> Set basic constraints if they are in the template

Makefile, internal/bcrypt_pbkdf/bcrypt_pbkdf.go, x509util/certificate_request_test.go, x509util/options_test.go, x509util/templates.go
Fixes JSON injection in IID templates.
Related to smallstep/certificates#435
=> Escape strings in X.509 templates.

README.md, go.mod, go.sum, keyutil/key.go, keyutil/key_test.go, tlsutil/cache.go, tlsutil/cache_test.go, tlsutil/renewer.go, tlsutil/renewer_test.go, tlsutil/server_credentials.go, tlsutil/server_credentials_test.go, tlsutil/utils.go, tlsutil/utils_test.go
This PR adds a new package including a refined version of the ca.Renewer in https://github.com/smallstep/certificates, as well as a ServerCredentials type that is a renewer for servers. The main difference is that the renew function can return different credentials depending on the SNI.
=> tlsutil package

pemutil/pem.go, pemutil/pem_test.go, pemutil/ssh.go
This PR allows to add `WithPasswordPrompt()` to encrypt a key on the `Serialize` function. Previous versions were only encrypting the key with `WithPassword()` or `WithPasswordFile()` were used.
=> Allow to ask for password to encrypt a key

pemutil/cosign.go, pemutil/cosign_test.go, pemutil/pem_test.go, pemutil/pkcs8.go, pemutil/pkcs8_test.go
This PR return `x509.IncorrectPasswordError` in and invalid password is detected on `DecryptPEMBlock`, `DecryptPKCS8PrivateKey` and `ParseCosignPrivateKey`.
Fixes #23
=> Incorrect password

sshutil/certificate.go, sshutil/certificate_test.go
This PR replaces the default RSA hash algorithm of x/crypto/ssh, SHA-1 (ssh-rsa) with SHA256 (rsa-sha2-256).
This new signature scheme has been supported since 2016 with OpenSSH 7.2. And on [OpenSSH 8.2](https://www.openssh.com/txt/release-8.2) was announced that ssh-rsa will be deprecated, and it has been removed in [OpenSSH 8.8](https://www.openssh.com/txt/release-8.8)
=> Use RSA-SHA2-256 when signing ssh certificates with an RSA key

randutil/random.go, randutil/random_test.go
We could call `Salt()` or the other way around, but it's only a little bit of duplicate code, so I figured it's OK to do like this.
=> Add Bytes() function

.github/workflows/release.yml, .github/workflows/test.yml, minica/minica.go, x509util/certpool_test.go, x509util/name.go, x509util/name_test.go
This PR adds ExtraNames to X.509 subject and issuers, so they can be templatized. One use of this is adding the deprecated DN emailAddress.
This PR also exposes the root signer in minica and fixes linter errors with Go 1.18.
=> Add ExtraNames

x509util/extensions.go, x509util/name.go, x509util/name_test.go
This commit will populate the subject ExtraNames in a certificate request from the information present in Names as long as it is not one of the default fields. This way, we can extract non-default fields as well as populate them in the final certificate if necessary.
It also uses the proper type for the deprecated email address attribute in the subject.
Related to smallstep/certificates#916
=> Populate ExtraNames from Names

keyutil/key.go, keyutil/key_test.go
This PR adds a new method, `keyutil.Insecure()`, that allows the creation of insecure RSA keys. This can be required, for example, by `step` to create legacy keys.
Note: I'm not using atomic.Bool because it is not available in 1.18
=> Insecure mode

README.md, fingerprint/fingerprint.go, fingerprint/fingerprint_test.go, sshutil/fingerprint.go, sshutil/fingerprint_test.go, x509util/fingerprint.go, x509util/fingerprint_test.go, x509util/utils.go, x509util/utils_test.go
This PR adds the new `fingerprint` package that unifies the logic for X.509 and SSH fingerprint, allowing at the same time supporting other hash functions required by `step`.
=> Add package fingerprint

.github/workflows/release.yml
crypto principal branch is `master` not `main`
=> Fix branch for ci job

kms/apiv1/requests.go, kms/yubikey/yubikey.go, kms/yubikey/yubikey_test.go
The YubiKey KMS allows to set pin and touch policies when a key is created, these policies are used when signing or decrypting with an asymmetric key in a slot.
The default pin policy is set to always and the touch policy to never, but now the values can be configurable.
`step-kms-plugin` will add `--pin-policy` and `--touch-policy` flags to be able to configure these.
=> YubiKey pin and touch policies

kms/kmsfs.go, kms/kmsfs_test.go
This PR wraps the fs.FS interface with an extra method to properly close the KMS. I first tried to use the context to do the same, but it was causing random panics in the Go runtime.
=> Add method to close the kms FSs

jose/types.go, jose/validate_test.go, keyutil/key.go
This PR changes the keypair verification to use the Equal method. Now the RSA key exponent is also verified, that was a problem with the previous version.
This method can also be simplified using crypto.Signer and an "Equaler" interface, but I've decided to leave it as it currently is.
=> Use Equal to verify a keypair

jose/generate_test.go, keyutil/key_test.go
This PR fixes key generation unit tests on Go 1.20rc2.
Go 1.20 introduces a [call](https://github.com/golang/go/blob/6ad27161f8d1b9c5e03fb3415977e1d3c3b11323/src/crypto/ecdsa/ecdsa.go#L155) to `randutil.MaybeReadByte(r io.Reader)` which reads a single byte from `r` with ~50% probability. This doesn't work properly with a tee reader that requires stable reads from rand.Reader.
Fixes #153
=> Fix test key generation tests with Go 1.20+

kms/awskms/awskms.go, kms/awskms/no_awskms.go, kms/awskms/signer.go, kms/azurekms/key_vault.go, kms/azurekms/no_azurekms.go, kms/azurekms/signer.go, kms/azurekms/utils.go, kms/capi/capi.go, kms/capi/no_capi.go, kms/cloudkms/cloudkms.go, kms/cloudkms/no_cloudkms.go, kms/cloudkms/signer.go, kms/pkcs11/pkcs11.go, kms/pkcs11/pkcs11_no_cgo.go, kms/sshagentkms/no_sshagentkms.go, kms/sshagentkms/sshagentkms.go, kms/yubikey/yubikey.go, kms/yubikey/yubikey_no_cgo.go
This PR adds support for passing the following tags to exclude a specific KMS from a binary:
- noawskms
- noazurekms
- nocapi
- nocloudkms
- nopkcs11
- nosshagentkms
- noyubikey
Fixes #163
=> Add tags to remove KMSs at compile time

keyutil/key.go, keyutil/key_test.go
This commit allows getting the public key from a `crypto.Signer` using the `keyutil.PublicKey(priv interface{})` method.
=> Allow crypto.Signer in keyutil.PublicKey() method

kms/azurekms/key_vault.go, kms/azurekms/key_vault_test.go, kms/azurekms/signer.go, kms/azurekms/utils.go, kms/azurekms/utils_test.go
This commit adds support US Government, China, and German Cloud environments.
A new URI parameter has been introduced to define the Azure environment. If that parameter is not set or it is set to public, the public cloud will be used.
Fixes smallstep/certificates#1276
=> Add support for sovereign clouds on Azure KeyVault

kms/azurekms/key_vault.go, kms/azurekms/key_vault_test.go, kms/azurekms/lazy_client.go, kms/azurekms/utils.go, kms/azurekms/utils_test.go
This commit removes the use of go-jose and the hack to unmarshal the HSM keys from Azure. Instead, it manually implements the decoding.
=> Manually extract the keys from the JWK

internal/bcrypt_pbkdf/bcrypt_pbkdf_test.go, kms/apiv1/requests.go, kms/pkcs11/benchmark_test.go, kms/pkcs11/pkcs11.go, kms/pkcs11/pkcs11_test.go, kms/sshagentkms/sshagentkms_test.go, kms/yubikey/yubikey.go, kms/yubikey/yubikey_test.go, x509util/extensions_test.go
This commit adds an optional permanent identifier in the CreateAttestation response. In the YubiKey KMS, the permanent identifier is the serial number in the attestation certificate.
This PR also files all linter errors.
=> Add permanent identifier in the CreateAttestation response

pemutil/pkcs8.go, x509util/extensions.go, x509util/extensions_test.go, x509util/options.go, x509util/options_test.go
This PR adds support for the following template functions:
* asn1enc, mustASN1Enc: given a string with or without a type, it encodes the ASN1 in base64.
* ans1Marshal, mustASN1Marshal: uses asn1.MarshalWithParams(), so it can support any type and options.
* asn1Seq, mustASN1Seq: given a list of base64(asn1) encoded strings, it builds a sequence of them, returning the base64 version of it.
* asn1Set, mustASN1Set: given a list of base64(asn1) encoded strings, it builds a set of them, returning the base64 version of it.
For example, you can build an extension like the following:
```go
{"id": "1.2.3.4", "value": {{ asn1Seq (asn1enc "YubiKey") (asn1enc "int:123456") | toJson }}}
```
=> Add support for asn1 methods in X509 templates

sshutil/fingerprint.go, sshutil/fingerprint_test.go
Before the change the fingerprint for an SSH certificate would
include the bytes that encode the certificate. An SSH fingerprint
should only be based on its public key.
This commit checks if the SSH key is actually an SSH certificate
and will fingerprint just the SSH certificate public key instead
of the entire certificate contents.
=> Fix SSH certificate fingerprint encoding

go.mod, go.sum, kms/azurekms/key_vault.go
This PR upgrades Azure's azidentity to v1.3.0, this version adds support for Workload Identity with AKS.
Fixes #222
=> Upgrade azidentity to v1.3.0

jose/types.go, pemutil/pkcs8.go
This commit increases the number of PBKDF2 iterations from 100k to 600k per OWASP recommendations.
=> Increase the number of PBKDF2 iterations to 600k

kms/pkcs11/pkcs11.go, kms/pkcs11/pkcs11_test.go, kms/pkcs11/setup_test.go
This commit adds support to automatically use the p11-kit-proxy module on the PKCS#11 KMS if no other module has been specified.
Fixes #259
cc: @dwmw2
=> Add automatic support for p11-kit

kms/tpmkms/tpmkms.go, kms/tpmkms/tpmkms_simulator_test.go
Before this PR AK attestation only worked for cases in which a (valid) AK certificate chain was already available, or when a new attestation was requested for a key attested by the AK. This PR adds support for obtaining an AK certificate for an AK if addressed directly (e.g. `tpmkms:name=my-ak;ak=true`) instead of addressing a key.
=> Support for AK-only attestation through CreateAttestation

kms/tpmkms/tpmkms_simulator_test.go, tpm/attestation/client_simulator_test.go, tpm/available/check.go, tpm/internal/close/close.go, tpm/internal/close/close_others.go, tpm/internal/close/close_windows.go, tpm/internal/open/open.go, tpm/internal/socket/socket.go, tpm/internal/socket/socket_others.go, tpm/internal/socket/socket_windows.go, tpm/rand/rand_simulator_test.go, tpm/simulator/simulator_disabled.go, tpm/simulator/simulator_enabled.go, tpm/tpm.go, tpm/tpm_simulator_test.go, tpm/tpm_test.go
On Linux and macOS a connection can now be made to a TPM that's exposed on a UNIX socket. This shouldn't be used for production purposes, but can be useful for development and testing with a TPM simulator. The [tpmutil.EmulatorReadWriteCloser](https://pkg.go.dev/github.com/google/go-tpm/tpmutil#EmulatorReadWriteCloser) is used to create the connection with the simulated TPM. 
A UNIX socket TPM will only be used when the TPM is initialized with a device name that contains the path to a UNIX socket. If the TPM instance is initialized with a `tpm.CommandChannel` or `simulator.Simulator` directly, these will take precedence over the UNIX socket path.
Connecting to a TPM using a UNIX socket is not supported on Windows.
=> Add UNIX socket TPM connection support

kms/yubikey/yubikey.go, kms/yubikey/yubikey_test.go
This commit fixes an error thrown by a YubiKey when signs or decrypts are performed simultaneously. We use a signer and decrypter protected by a common mutex to do this.
Fixes smallstep/certificates#1463
=> Create synchronized signers and decrypters for YubiKeys

tpm/manufacturer/manufacturers.go
Before:
```console
$ sudo step tpm info
+------------------+--------------------------------------+
| Version          | TPM 2.0                              |
| Interface        | kernel-managed                       |
| Manufacturer     | unknown (AMZN, 414D5A4E, 1095588430) |
| Vendor Info      | NitroTPMv1.0                         |
| Firmware Version | 8217.4131                            |
+------------------+--------------------------------------+
```
After:
```console
$ sudo step tpm info
+------------------+--------------------------------------------------+
| Version          | TPM 2.0                                          |
| Interface        | kernel-managed                                   |
| Manufacturer     | Amazon Web Services (AMZN, 414D5A4E, 1095588430) |
| Vendor …
```
=> Add `AMZN` (AWS; NitroTPM) as known TPM manufacturer

kms/tpmkms/errors.go, kms/tpmkms/tpmkms.go, kms/tpmkms/tpmkms_simulator_test.go
This way a user of the package can try to obtain a new AK certificate when it has expired.
In addition to that, also return errors for other certificate state errors, such as not yet valid and it not being available.
=> Return an error when AK certificate is expired

kms/tpmkms/errors.go, kms/tpmkms/tpmkms.go, kms/tpmkms/tpmkms_simulator_test.go, kms/tpmkms/tpmkms_test.go, kms/uri/uri.go, kms/uri/uri_test.go
To support early renewal of AK certificates as part of a call to `CreateAttestation` in `TPMKMS`, the KMS should detect if an AK certificate is still within a specific percentage of it its original lifetime. This PR adds support for this check and introduces two new KMS URI options that influence the behavior:
* `disable-early-renewal=true`: disables the early renewal check and thus won't return an error when the certificate hasn't actually expired yet.
* `renewal-percentage=<int>`: sets the percentage of the lifetime after which the AK certificate will be considered to expire soon, and renewal will thus be tried.
=> Add support for early renewal for AK identity certificates

internal/templates/validate.go, internal/templates/validate_test.go, kms/capi/capi_no_windows.go, kms/capi/ncrypt_windows.go, kms/tpmkms/no_tpmkms.go, sshutil/options.go, sshutil/options_test.go, sshutil/templates.go, x509util/options.go, x509util/options_test.go, x509util/templates.go
This commit adds functions that return a map of the functions used by templates. `step-ca` currently fails to create a provisioner with a template using the new functions because the validation of the template fails.
=> Template funcs

kms/apiv1/options.go, kms/apiv1/requests.go, kms/kms.go, kms/softkms/softkms.go
When configuring SCEP decrypters, primarily when doing so through Remote Administration, it can happen that a password is required for the decrypter key. If the user doesn't provide a value for the password when a password is required, the CA will prompt for the password, but will do so on the CA side as part of the running process; not on the CLI side. It will do so twice, even: first when initializing the provisioner to be able to validate it, then to load it into the actual running process. 
By supporting a `PasswordPrompter` to be set and providing a `NonInteractivePasswordPrompter` that returns an error by default, the password prompt is effectively immediately returned with an error instead of waiting for input on the CA side. This is an example usage:
```golang
decrypter, err := …
```
=> Add `PasswordPrompter` to decrypter and signer requests

x509util/extensions.go, x509util/extensions_test.go, x509util/options_test.go
This commit allows the use of the "bool:" or "boolean:" prefix to ASN.1 encode boolean values like true or false.
Fixes #340
=> Allow to encode boolean types

jose/validate.go, jose/validate_test.go, kms/apiv1/options.go, kms/apiv1/options_test.go, kms/apiv1/registry.go, kms/kms.go
This commit introduces the helper `kms.TypeOf`, which returns the type of a URI. It also normalizes the type when necessary.
It also adds a commit to be able to validate JWKs that use an OpaqueSigner.
=> Add helpers to return the kms from an uri

tpm/tss2/encode.go, tpm/tss2/encode_test.go, tpm/tss2/other_test.go, tpm/tss2/signer.go, tpm/tss2/signer_test.go, tpm/tss2/simulator_test.go, tpm/tss2/tpm_test.go
This PR adds a signer implementation for TSS2 keys, it also adds new methods to marshal those keys to PEM.
=> Add signer implementation to TSS2 keys

tpm/tpm.go
After adding support for interacting with TPMs via UNIX sockets, opening the TPM was broken on Windows, because that specific case wasn't properly checked in code. This PR checks if a UNIX socket TPM command channel is supported, and ignores the error if that's not the case.
=> Don't break command channel initialization on `socket.ErrNotSupported`

kms/apiv1/requests.go, kms/cloudkms/cloudkms.go, kms/cloudkms/cloudkms_test.go
This commit adds a new option DestroyRetentionPeriod to the kms.CreateKey method to define the period which a deleted key is recovarable. Currently this is only implemented by cloudkms.
Fixes #363
=> Add a configurable retention period for cloudkms keys

go.mod, go.sum, tpm/tpm_simulator_test.go
This commit upgrades smallstep/go-attestation to the last commit in the surrogate branch. The new version includes a fix for RSAPSS signing from smallstep/go-attestation#4.
=> Upgrade go-attestation

kms/yubikey/yubikey.go, kms/yubikey/yubikey_test.go
This commit adds a cache of yubikey connections so the same card can be open more than once by the same application.
=> Implement yubikey connection cache

tpm/internal/key/key.go, tpm/tss2.go, tpm/tss2/encode.go
The default handle 0x81000001 (2164260865) overflows int if compiled on a 32 bits architecture (linux/386). This change changes the type of the handles to tpmutil.Handle that are uint32.
=> Do not overflow default handle on 32 bits architectures

kms/pkcs11/pkcs11.go, kms/pkcs11/pkcs11_test.go
This commit removes the enforcement of a pin when a pkcs11 kms is initialized. Some soft pkcs11 implementations, like NSS's soft token, have an empty pin by default.
=> Do not enforce pin on pkcs11 kms

kms/pkcs11/pkcs11.go
Fixed that wrong the first time -.-
=> Fix `softoken` spelling

kms/softkms/softkms.go, kms/softkms/softkms_test.go
This commit adds SigningKey to the softkms CreateKey response. This field is not used by CreateSigner as Signer is present, but the rest of the key managers return the SigningKey.
=> Add SigningKey to softkms CreateKey response

kms/apiv1/options.go, kms/apiv1/options_test.go, kms/mackms/mackms.go, kms/mackms/mackms_test.go
This commit implements the "Is(target error) bool" interface to apiv1 errors so we can compare them with errors.Is even if the message is not empty.
=> Allow to compare kms errors with errors.Is

kms/cloudkms/cloudkms.go, kms/cloudkms/decrypter.go, kms/cloudkms/decrypter_test.go, kms/cloudkms/signer.go, kms/cloudkms/signer_test.go
This commit adds URI support for the CloudKMS decrypter and the NewSigner method.
Before this change, CreateDecrypter required the raw resource name, while the rest of the methods allow either a raw resource or a URI like `cloudkms:name` or `cloudkms:resource=name`.
=> Add URI support for CloudKMS decrypter

kms/cloudkms/cloudkms.go, kms/cloudkms/cloudkms_test.go, kms/cloudkms/decrypter.go, kms/cloudkms/decrypter_test.go, kms/cloudkms/signer.go, kms/cloudkms/signer_test.go
An error similar to the one below occurred:
`Resource name 'cloudkms:projects/staging-a23d/locations/global/keyRings/b84b7b21-0993-43fd-b0c4-3c8cd204e635/cryptoKeys/root-key/cryptoKeyVersions/1' does not match pattern 'projects/([^/]{1,100})/locations/([a-zA-Z0-9_-]{1,63})/keyRings/([a-zA-Z0-9_-]{1,63})/cryptoKeys/([a-zA-Z0-9_-]{1,63})/cryptoKeyVersions/([a-zA-Z0-9_-]{1,63})'."`
Not all cases that interact with the actual GCP API used the right format for the key URI. The code was changed to use a GCP resource name while (pre)loading resources from GCP. The case was not caught in unit tests yet, because those rely primarily on mocks and there were no assertions in the mocks. Added some really basic and primitive ones as a means of guard rails. They won't catch everything now, but should …
=> Fix GCP CloudKMS resource URIs sometimes starting with `cloudkms:`

jose/parse.go
The X5cInsecure certificate is used by step-ca to renew certificates without using mTLS, usually expired certificates. `Certificate.Verify` defaults to require ServerAuth if no KeyUsages is set as an option. Due to how these tokens are used, it makes more sense to require only ClientAuth.
Note that a few lines after this check is also made:
```go
if leaf.KeyUsage&x509.KeyUsageDigitalSignature == 0 {
return nil, nil, errors.New("certificate used to sign x5cInsecure token cannot be used for digital signature")
}
```
Related to smallstep/certificates#1843
=> Require ClientAuth when verifying an X5cInsecure certificate

keyutil/key.go, kms/tpmkms/tpmkms.go, kms/tpmkms/tpmkms_simulator_test.go, kms/tpmkms/tpmkms_test.go
This commit implements the experimental DeleteKey in the `tpmkms`. It also converts all `tpm.ErrNotFound` to `apiv1.NotFoundError{}` and fixes a linter warning in keyutil.
=> Implement DeleteKey on tpmkms

internal/darwin/security/security_darwin.go, kms/mackms/signer.go, kms/mackms/signer_test.go
This commit adds experimental support for the ECDH exchange using macOS keychain.
cc: @hslatman
=> Add support for ECDH exchange using MacKMS

internal/templates/funcmap.go, internal/templates/funcmap_test.go, sshutil/certificate.go, sshutil/certificate_test.go, sshutil/testdata/date.tpl, x509util/certificate.go, x509util/certificate_test.go, x509util/options_test.go, x509util/testdata/example.tpl, x509util/testdata/fullsimple.tpl
This commit allows setting the validity bounds on X.509 and SSH certificates using templates. 
It also adds the template method `toTime`, which makes it easier to format a timestamp to RFC3339. This format is compatible with Go's `time.Time` when `json.Unmarshal` is used. There are similar methods to do this in the sprig library, but they require you to specify the format string. For example, these methods will return a valid string that can be unmarshaled to `time.Time`:
```go
{{ date "2006-01-02T15:04:05Z07:00" .Token.nbf | toJson }}
{{ dateInZone "2006-01-02T15:04:05Z07:00" .Token.nbf "UTC" | toJson }}
{{ toTime .Token.nbf | toJson }}
```
=> Add support validities in templates

internal/templates/funcmap.go, internal/templates/funcmap_test.go, x509util/certificate_test.go
This PR improves the functions added in https://github.com/smallstep/crypto/pull/534 with some usability changes. 
* `toTime 1719970524` returns a `time.Time` in UTC from a time or a Unix epoch.
* `formatTime (now)`: from a time or Unix epoch returns a time string using RFC3339 format UTC.
* `parseTime` and `mustParseTime`:
* `parseTime`: returns the current `time.Time` in UTC.
* `parseTime "2024-07-03T01:30:39Z"`: parses the given time using RFC3339.
* `parseTime "time.UnixDate" "Tue Jul  2 18:31:04 PDT 2024"`: parses a time using a given format.
* `parseTime "time.UnixDate" "Tue Jul  2 18:31:04 PDT 2024" "America/Los_Angeles"`: parses a time with the given format and time zone.
* `toTimeLayout`  returns a layout format from the given name.
* `toTimeLayout "RFC3339"` returns …
=> Improve time functions

internal/darwin/corefoundation/core_foundation_darwin.go, internal/darwin/security/security_darwin.go, kms/apiv1/options.go, kms/apiv1/requests.go, kms/mackms/mackms.go, kms/mackms/mackms_test.go
In follow up PRs I'd like to add:
- Support in PKCS11
- Support in TPMKMS
- Support in CAPI?
- Support for searching certificates?
=> Add `SearchKeys` functionality to MacKMS

tpm/ak.go, tpm/ak_test.go, tpm/attestation/client_test.go, tpm/ek_test.go, tpm/errors.go, tpm/key.go, tpm/key_test.go, tpm/signer.go, tpm/storage/blackhole.go, tpm/storage/blackhole_test.go, tpm/storage/dirstore.go, tpm/storage/dirstore_test.go, tpm/storage/errors.go, tpm/storage/feedthrough.go, tpm/storage/feedthrough_test.go, tpm/storage/types_test.go, tpm/tpm.go, tpm/tpm_simulator_test.go, tpm/tpm_test.go, tpm/tss2/signer_test.go
The goal of the blackhole storage is to be able to use an instance of `tpm.TPM` for operations that don't require an (metadata) storage. In some usages it could result in an error or even a panic, because it's not clear enough that some operations require an actual storage implementation for the operations to succeed. 
This commit changes the behavior of the blackhole storage. It now returns a sentinel error for operations that require a storage to be successful. The sentinel error is handled in the `tpm` package wherever a storage operation takes place.
=> Return a sentinel error when no storage is configured when required

kms/capi/capi.go
This PR removes extraneous calls to `CertFreeCertificateContext` in `DeleteCertificate` within the `capi` package. According to the Windows [library documentation](https://learn.microsoft.com/en-us/windows/win32/api/wincrypt/nf-wincrypt-certdeletecertificatefromstore):
> The CertDeleteCertificateFromStore function always frees pCertContext by calling the [CertFreeCertificateContext](https://learn.microsoft.com/en-us/windows/desktop/api/wincrypt/nf-wincrypt-certfreecertificatecontext) function, even if an error is encountered. Freeing the [context](https://learn.microsoft.com/en-us/windows/desktop/SecGloss/c-gly) reduces the context's [reference count](https://learn.microsoft.com/en-us/windows/desktop/SecGloss/r-gly) by one. If the reference count reaches zero, memory allocated for the …
=> Remove extraneous 'CertFreeCertificateContext' in capi.

kms/mackms/mackms.go, kms/mackms/mackms_test.go, kms/uri/uri.go, kms/uri/uri_test.go
This commit allows to create, get, sign, and other operations using keys without a tag.
By default, the default tag used by the mackms package is `com.smallstep.crypto`. If we want to create or get a key using the URI `mackms:label=test`, the `mackms` package will assume that the default tag is being used.
The default tag can be changed using the tag parameter in the URI, e.g., `mackms:label=test;tag=my-tag`. But if we want not to use a tag, we need to provide the tag parameter empty, e,g., `mackms:label=test;tag=`. 
Programs using the `mackms` package can also set the `mackms.DefaultTag` to any other value, if it is set to empty, the created keys will not have a tag.
Fixes #595
=> Add support for using mackms keys with no tags

internal/darwin/security/security_darwin.go
This commit fixes the conversion of CFStringRef to strings when CFStringGetCStringPtr fails. It also fixes panics when extracting attributes not present in the key. One example is extracting the tag in the mackms SearchKeys method if a key doesn't have one.
=> Fix cgo data conversion for bytes and strings

kms/mackms/mackms.go, kms/mackms/mackms_test.go
This function allows you to retry the load of a key without tags if the original URL didn't have one.
This is used only in GetPublicKey and CreateSigner. It is not used in SearchKeys as duplicate keys must be removed.
cc: @joshdrake
=> Allow to retry with no tags when loading privatekeys

kms/pkcs11/pkcs11.go, kms/pkcs11/pkcs11_test.go
This commit adds the max-sessions parameter to limit the maximum number of open sessions we will keep with the HSM before reusing a previous one. It defaults to the crypto11 default, 1024.
=> Add max-sessions parameter on pkcs11 kms

kms/yubikey/yubikey.go, kms/yubikey/yubikey_test.go
This commit adds support for imported keys in YubiKey KMS. Now, we attempt to retrieve a key using go-piv's KeyInfo that supports both imported and generated keys. This functionality is only available from YubiKey firmware  5.3.0. We will fallback to Attest and Certificate methods that are available in older versions.
Fixes #655
=> Add support for imported keys

kms/uri/uri.go, kms/uri/uri_test.go, kms/yubikey/yubikey.go, kms/yubikey/yubikey_test.go
This commit adds the yubikey attribute management-key-source. This attribute is used to pass the yubikey management key from a file.
Fixes smallstep/step-kms-plugin#207
=> support for yubikey management key from a file

internal/templates/funcmap_test.go, x509util/certificate_test.go
The `dateInZone` template function would instantiate a new time using `time.Now()` when a type was provided that it doesn't handle explicitly. This could occasionally result in a mismatch in the time being reported and compared against, usually being the time the test was started.
Also see https://github.com/Masterminds/sprig/blob/8cb06fe3c8b0f1163c26b0a558669da72ee14656/date.go#L25-L48
Fixes #677
=> Fix flaky behavior for tests using sprig's `dateInZone`

jose/parse.go, jose/parse_test.go, jose/types.go, jose/types_test.go
This commit adds support for custom `crypto.Signer` types for signing tokens. With this, one can use the signer implemented in a KMS or even `step` + `step-kms-plugin` to sign JWTs.
=> Extend jose.NewSigner support for other types

internal/utils/asn1.go, internal/utils/asn1_test.go, nssdb/keys.go, nssdb/keys_test.go, x509util/certificate_request.go, x509util/extensions.go, x509util/utils.go
When importing a private key into an NSS database with a certificate, the certificate common name is used as the value of the CKA_SUBJECT attribute on the key object. This fixes the serialization to work when the CN contains characters that aren't valid for the asn1 printable string type.
💔Thank you!
=> Use utf8 string for private key subject with non-printable characters

kms/softkms/softkms.go, kms/softkms/softkms_test.go
This commit fixes the opening of files in `softkms` when an URI and a full path are used. e.g., `softkms:/path/to/file.pem`
=> Fix open files with a full path in softkms

kms/pkcs11/pkcs11.go, kms/pkcs11/pkcs11_test.go
This commit sets the option LoginNotSupported if no pin is set. Servers using the p11-kit server protocol might not have a pin.
@hslatman should we do that? Or add an extra option? 
We don't have any other way to set a pin, so doing this I think is ok for now.
=> Add support for tokens with no pins

x509util/certificate_test.go, x509util/extensions.go, x509util/extensions_test.go, x509util/marshal_utils.go, x509util/marshal_utils_test.go
This commit fixes templates with policy identifiers on a program with the go.mod set to 1.24. With Go 1.24, the policies extension is marshaled using the values in the Policies field, but with Go 1.23 or a previous version, the marshaled field is PolicyIdentifiers.
This commit sets the same values on Policies and PolicyIdentifiers, ensuring that the templates with policies work in different versions of Go.
Fixes #738
=> Fix templates with policies with Go 1.24

internal/darwin/corefoundation/core_foundation_darwin.go, internal/darwin/security/security_darwin.go, kms/mackms/mackms.go, kms/mackms/mackms_test.go
This PR adds support for storing certificates in the Data Protection Keychain. This functionality is only available for code-signed applications.
Additionally, this commit includes a fix that enables retrieving a key from the Data Protection Keychain or not based on URI parameters. 
This last fix slightly changes the behavior: previously, keys stored in the Secure Enclave could be retrieved without specifying `se=true`, but it was not possible to retrieve the proper key if a key in the Secure Enclave shares the same label as a key in the login keychain.
=> Add support for the Data Protection Keychain

internal/bcrypt_pbkdf/bcrypt_pbkdf.go, internal/bcrypt_pbkdf/bcrypt_pbkdf_test.go
CI was flaky, sometimes triggering on the underscore, and sometimes not. For example, this [merge commit](https://github.com/smallstep/crypto/actions/runs/16138378521/job/45539789357) failed, whereas the [PR itself](https://github.com/smallstep/crypto/pull/800) was green. Let's deal with it once and for all.
=> Remove underscore from `bcrypt_pbkdf` package

kms/capi/capi.go
Signature verification fails on Windows with capi kms when signing with EC p-521 keys since r and s are supposed to be 66 bytes each.
Fix https://github.com/smallstep/cli/issues/1453.
💔Thank you!
=> Fix conversion of raw ecdsa p-521 signature to asn encoded

kms/azurekms/key_vault.go
This commit prioritizes the `hsm=true` flag in the URI to create a key in an Azure HSM Key Vault. Before this change, `step-kms-plugin` required the use of the flag `--protection-level HSM` to create a key in the HSM.
Fixes smallstep/step-kms-plugin#252
=> Use protection level HSM if it's given in the URI

go.mod, internal/termutil/termutil.go, kms/uri/uri.go, kms/uri/uri_test.go
This commit adds the pin-prompt option to the Pin method to allow a user to ask for a pin using the terminal.
Fixes smallstep/cli#1460
=> Add pin-prompt option

x509util/extensions.go, x509util/extensions_test.go
Accepting `NonRepudiation` when unmarshalling `keyUsage`.
Better user experience for users that are used to the old name (e.g., from OpenSSL, which still uses the old name exclusively).
I didn't add any, because I don't think this should be advertised — but it's nice when it works when somebody attempts it.
smallstep/certificates#2348
ITU-T X.509 (10/2019) section 9.2.2.3 [1] defines 'contentCommitment' as the current name for what had previously been called 'nonRepudiation', and deprecates the old name:
> It is not incorrect to refer to this keyUsage bit using the identifier
> nonRepudiation. However, the use of this identifier has been
> deprecated.
The old name is still widely used, though — for example, OpenSSL still supports nonRepudiation exclusively. It is therefore not surprising …
=> Accept nonRepudiation when unmarshalling keyUsage

kms/yubikey/yubikey.go, kms/yubikey/yubikey_test.go
This commit includes the extra intermediate certificates added to YubiKeys 5.7.4+ on PIV attestation.
See smallstep/certificates#2355
=> Support for YubiKey 5.7.4+

.github/workflows/ci.yml, go.mod, go.sum
CodeQL tries to run `make build`, but that doesn't exist in this repository. Using `go build ./...` should allow CodeQL to analyze the code for all packages.
Depends on changes in https://github.com/smallstep/workflows/pull/265.
Replaces #861.
=> Set `go build ./...` as CodeQL build command
